### ISSUE TITLE
opensim module failed in python

### ISSUE THREAD

**Issue by frstrtr** [qualisys/paf-resources#4]
After OpenSim installation
(step 2 from the readme.MD file in the OpenSim example folder)
I still can't export the OpenSim module 

I got this error message:

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OpenSim 4.1\sdk\Python\opensim\__init__.py", line 1, in <module>
    from .simbody import *
  File "C:\OpenSim 4.1\sdk\Python\opensim\simbody.py", line 18, in <module>
    _simbody = swig_import_helper()
  File "C:\OpenSim 4.1\sdk\Python\opensim\simbody.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: Module not found.

**Comment by frstrtr** [comment]
Solved:
OpenSim's DLLs are not on your PATH. In a command window, you could achieve this with a command like "set PATH=C:\OpenSim 4.0\bin;%PATH%"
